[db_all:children]
oracle
postgresql
mysql
mongodb

[oracle]
# oracle-db-01 ansible_host=10.0.10.21

[postgresql]
# pg-db-01 ansible_host=10.0.20.21

[mysql]
# mysql-db-01 ansible_host=10.0.30.21

[mongodb]
# mongo-db-01 ansible_host=10.0.40.21
